server:
  port: 8002
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proveedores_leche
    username: postgres
    password: sandia01
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect